import grp conditionally
This commit only imports grp on *nix systems, since it isn't available on windows systems, and it will throw an error

 * https://github.com/BusKill/buskill-app/issues/78#issuecomment-2158841322

  Traceback (most recent call last:):
   File "main .py", line 22 in <module>
    import platform, os, grp
  ModuleNotFoundError: No module named 'grp'