attempt to fix clone errors
This commit updates the macos build script to clone the buskill deps repo using a depth of 1 and without tags, per:

 * https://serverfault.com/questions/1056419/git-wsl2-ssh-unexpected-disconnect-while-reading-sideband-packet

I'm doing this because I keep getting errors on the clone when attempting to run the build script on our mac mini

  + git clone https://github.com/BusKill/buskill-app-deps.git
  Cloning into 'buskill-app-deps'...
  error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
  error: 4973 bytes of body are still expected
  fetch-pack: unexpected disconnect while reading sideband packet
  fatal: early EOF
  fatal: fetch-pack: invalid index-pack output